-- {-# LANGUAGE EmptyDataDecls             #-}
-- {-# LANGUAGE FlexibleContexts           #-}
-- {-# LANGUAGE GADTs                      #-}
-- {-# LANGUAGE GeneralizedNewtypeDeriving #-}
-- {-# LANGUAGE MultiParamTypeClasses      #-}
-- {-# LANGUAGE OverloadedStrings          #-}
-- {-# LANGUAGE QuasiQuotes                #-}
-- {-# LANGUAGE TemplateHaskell            #-}
-- {-# LANGUAGE TypeFamilies               #-}

-- module Nightwatch.DB(createAria2Log
--   ,recordAria2Response
--   ,createDownload
--   ,fetchDownloadByGid
--   ,fetchAria2LogByRequestId
--   ,authenticateChat
--   ,SqlPersistM
--   ,Entity(..)
--   ) where
-- import Control.Monad.IO.Class  (liftIO)
-- import Database.Persist
-- import Database.Persist.Sqlite
-- import Database.Persist.TH
-- import Nightwatch.Types
-- import Data.Time (UTCTime, getCurrentTime)
-- import Nightwatch.DBTypes

